### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by Suburbanno** [GLodi/GitNav#1]

**Comment by GLodi** [comment]
Still need to develop some core components. I'll update README with a few screenshots shortly.

**Comment by Suburbanno** [comment]
ok, thanks

**Comment by blaccout47** [comment]
What exactly is that

**Comment by Suburbanno** [comment]
@GLodi hey guy, pls release apk <3

**Comment by GLodi** [comment]
@Suburbanno sorry, totally forgot. I've just released it as 1.0. Keep in mind that this app was just a test for me. It's not feature-complete and I haven't used any kind of architecture. I've considered implementing MVP, but it would require too much work and I've moved on to another project.
