### ISSUE TITLE
Don't know what this is or means 

### ISSUE THREAD

**Issue by blaccout47** [GLodi/GitNav#2]
set BASE_DIR=. set CLASSPATH=%BASE_DIR%\SIProp-2.0.jar;%BASE_DIR%\lib\nist-sdp-1.0-patch.zip;%BASE_DIR%\lib\jain-sip-api-1.2-patch.zip;%BASE_DIR%\lib\jain-sip-ri-1.2-patch.zip;%BASE_DIR%\lib\siprop2-f3.jar;%BASE_DIR%\lib\activation-1.1.jar;%BASE_DIR%\lib\activeio-core-3.0.0-incubator.jar;%BASE_DIR%\lib\activemq-core-4.1.1.jar;%BASE_DIR%\lib\activemq-ra-4.1.1.jar;%BASE_DIR%\lib\aopalliance-1.0.jar;%BASE_DIR%\lib\backport-util-concurrent-2.2.jar;%BASE_DIR%\lib\backport-util-concurrent-3.0.jar;%BASE_DIR%\lib\classworlds-1.0.1.jar;%BASE_DIR%\lib\commons-beanutils-core-1.7.0.jar;%BASE_DIR%\lib\commons-codec-1.3.jar;%BASE_DIR%\lib\commons-collections-3.1.jar;%BASE_DIR%\lib\commons-httpclient-3.0.jar;%BASE_DIR%\lib\commons-logging-1.1.jar;%BASE_DIR%\lib\commons-pool-1.2.jar;%BASE_DIR%\lib\concurrent.jar;%BASE_DIR%\lib\derby-10.2.2.0.jar;%BASE_DIR%\lib\dnsjava-2.0.5.jar;%BASE_DIR%\lib\geronimo-connector-2.0.1.jar;%BASE_DIR%\lib\geronimo-ejb_2.1_spec-1.1.jar;%BASE_DIR%\lib\geronimo-j2ee-connector_1.5_spec-1.1.jar;%BASE_DIR%\lib\geronimo-j2ee-jacc_1.0_spec-1.1.jar;%BASE_DIR%\lib\geronimo-j2ee-management_1.0_spec-1.1.jar;%BASE_DIR%\lib\geronimo-jms_1.1_spec-1.1.jar;%BASE_DIR%\lib\geronimo-jta_1.1_spec-1.1.jar;%BASE_DIR%\lib\geronimo-servlet_2.4_spec-1.1.jar;%BASE_DIR%\lib\geronimo-transaction-2.0.1.jar;%BASE_DIR%\lib\howl-1.0.1-1.jar;%BASE_DIR%\lib\JainSIP-Parser-1.2.jar;%BASE_DIR%\lib\jencks-2.1.jar;%BASE_DIR%\lib\jetty-6.0.2.jar;%BASE_DIR%\lib\jetty-6.1.5.jar;%BASE_DIR%\lib\jetty-client-6.1.5.jar;%BASE_DIR%\lib\jetty-management-6.1.5.jar;%BASE_DIR%\lib\jetty-util-6.0.2.jar;%BASE_DIR%\lib\jetty-util-6.1.5.jar;%BASE_DIR%\lib\log4j-1.2.13.jar;%BASE_DIR%\lib\log4j-1.2.14.jar;%BASE_DIR%\lib\mail-1.4.jar;%BASE_DIR%\lib\mina-core-1.1.3.jar;%BASE_DIR%\lib\servicemix-audit-3.2.jar;%BASE_DIR%\lib\servicemix-beanflow-3.2.jar;%BASE_DIR%\lib\servicemix-components-3.2.jar;%BASE_DIR%\lib\servicemix-core-3.2.jar;%BASE_DIR%\lib\servicemix-http-3.2.jar;%BASE_DIR%\lib\servicemix-jbi-3.2.jar;%BASE_DIR%\lib\servicemix-services-3.2.jar;%BASE_DIR%\lib\servlet-api-2.4.jar;%BASE_DIR%\lib\siprop2-f3.jar;%BASE_DIR%\lib\slf4j-api-1.3.0.jar;%BASE_DIR%\lib\slf4j-simple-1.3.0.jar;%BASE_DIR%\lib\smack.jar;%BASE_DIR%\lib\smackx.jar;%BASE_DIR%\lib\spring-2.0.4.jar;%BASE_DIR%\lib\spring-aop-2.0.6.jar;%BASE_DIR%\lib\spring-beans-2.0.6.jar;%BASE_DIR%\lib\spring-context-2.0.6.jar;%BASE_DIR%\lib\spring-core-2.0.6.jar;%BASE_DIR%\lib\spring-dao-2.0.6.jar;%BASE_DIR%\lib\spring-jmx-2.0.6.jar;%BASE_DIR%\lib\spring-remoting-2.0.6.jar;%BASE_DIR%\lib\stax-api-1.0.1.jar;%BASE_DIR%\lib\woden-1.0.0M6.jar;%BASE_DIR%\lib\wsdl4j-1.6.1.jar;%BASE_DIR%\lib\wstx-asl-3.2.2.jar;%BASE_DIR%\lib\xalan-2.7.0.jar;%BASE_DIR%\lib\xbean-classloader-3.2.jar;%BASE_DIR%\lib\xbean-kernel-3.2.jar;%BASE_DIR%\lib\xbean-server-3.2.jar;%BASE_DIR%\lib\xbean-spring-3.2.jar;%BASE_DIR%\lib\xercesImpl-2.8.1.jar;%BASE_DIR%\lib\xml-apis-1.3.04.jar;%BASE_DIR%\lib\xstream-1.1.2.jar; java -classpath %CLASSPATH% -Dsiprop.properties=./conf/siprop.properties -Dlogger.properties=./conf/logger.properties org.siprop.v2.B2BUAMain

**Comment by GLodi** [comment]
Hi, 
can you show me the logcat and describe how you got this error?
