### ISSUE TITLE
Filter when searching....

### ISSUE THREAD

**Issue by Suburbanno** [GLodi/GitNav#4]
Could you add filter to look for repositories and users? This is for our repositories and stars too (recently active, Most stars)

**Comment by GLodi** [comment]
Yes, I'll definitely give it a try.
I didn't pay much attention when I implemented the search function, and now with the new Google Play Console I've noticed a lot of crashes there, particularly when searching for code.
I should also be able to implement a filter for user profile. So that, when you click on a user, his repositories will be sorted for most starred or recently active.

**Comment by Suburbanno** [comment]
It will be wonderful, best github app currently, I'm quite anxious

**Comment by Suburbanno** [comment]
hey, release beta? please :(

**Comment by GLodi** [comment]
Still need to implement a couple of activities. Then I'll make a beta release here, so you can check the filters :)

**Comment by Suburbanno** [comment]
thanks guy <3

**Comment by Suburbanno** [comment]
:(

**Comment by GLodi** [comment]
I've just finished the search function! I'm gonna make a release today, but keep in mind that the repository activity is not implemented yet, so you won't be able to see repos.

**Comment by GLodi** [comment]
Done. You can download the apk from the releases page and put it on your device. Again a few points:
 - You can't see repos as I haven't implemented the repo activity yet.
 - The code section of the search function doesn't do anything yet. I'm having some trouble with it.
I'd like to ask you if you think is necessary to add filters to the search function as well. For example you search for repos named "Google" and the results are filtered by number of stars. I've tried it a bit, but the results that I get are weird and sometimes have nothing to do with the query.

**Comment by Suburbanno** [comment]
yeah, need to add these filters, the added filter is ok, but here where I marked with a green circle should show the time the repository was updated, ex: "Updated 3 minutes ago" or "3 minutes ago" , you understand?
![photo_2017-06-01_13-25-44](https://cloud.githubusercontent.com/assets/13632826/26689931/def0ee3a-46cd-11e7-9f05-3c9260b86cc1.jpg)

**Comment by GLodi** [comment]
Damn, you are right. I'll look into that. Thanks!

**Comment by Suburbanno** [comment]
Ok

**Comment by GLodi** [comment]
I made a new beta release with that fix and the search activity filters! Check it out and tell me what you think :)

**Comment by Suburbanno** [comment]
Oh, overall it's all working, I think the search is a little slow to show the results, and sometimes this error, but overall is fine, you intend to give a new look to the profile etc?
![photo_2017-06-02_13-58-12](https://cloud.githubusercontent.com/assets/13632826/26736219/8c81d3f2-479b-11e7-979e-a84217aaf124.jpg)

**Comment by GLodi** [comment]
Yeah, I've noticed. Having implemented a search function that makes network requests as you type, GitHub API is not very happy. Sometimes it randomly drops the request, sometimes it tells you that you have reach the API limit or that you are making too many requests at once. I'll look into that a bit more, but I'm afraid that I'll have to disable the search-as-you-type feature.
Regarding the speed I can't do much about it. The less specific the query, the more work github has to do to give you the results.

I was thinking about changing the profile activity to something like this (image not mine, taken from google images):
![tlgbqge](https://cloud.githubusercontent.com/assets/4631114/26736713/94e38032-47c7-11e7-82dd-0060cf653255.png)

**Comment by Suburbanno** [comment]
I liked very much...
Will you show the contributions panel? And another, can we have github settings? Change profile photo, update description, basic settings do you understand? And will it have a dark theme? Sorry for so many requests, I really like being inside the projects.

**Comment by GLodi** [comment]
The contributions panel is a great idea. I've seen another github app that shows it. I still have no idea how to implement it.
Certainly I could put a menu inside the UserActivity that would allow the user to edit his profile.
Yes, I already planned to implement a dark theme.
Any idea is welcomed :)

**Comment by Suburbanno** [comment]
Could you add notifications?

**Comment by GLodi** [comment]
Mmh... that's trickier. I'm not sure how to implement it, but I'll look into it.

**Comment by Suburbanno** [comment]
ok

**Comment by GLodi** [comment]
What do you think of this new UserActivity concept?

![ezgif-1-dc3852b9d1](https://user-images.githubusercontent.com/4631114/26850687-ae89239a-4b08-11e7-82b1-ba7314268e92.gif)

**Comment by Suburbanno** [comment]
holy shit, very perfect, BETA PLEASEEEE, the best

**Comment by Suburbanno** [comment]
hey add notifications please

**Comment by Suburbanno** [comment]
hey, news?

**Comment by GLodi** [comment]
Yes! I'm working on making all activities ready for configuration change (so that they work even if you rotate your screen). UserActivity (the one I showed you with the gif) is complete, now it even has the user's contribution graph. I'll make a release with all the new features shortly so that you can try it out.

**Comment by GLodi** [comment]
GitNav 1.3 released!

**Comment by Suburbanno** [comment]
my god, it's getting wonderful, I can not wait to open the repositories and can use it all, one more question, will it support organizations?

**Comment by GLodi** [comment]
Mmmh I'll need to look into that. I'm not sure how Organizations API work.

**Comment by Suburbanno** [comment]
understand, everything was really cute and fast, the transitions are not slow like the other applications of the genre, I hope in the future it will be really complete, with support for problems and sending requests and wiki etc ... I am willing to Continue giving suggestions and motivating you with the project ♥

**Comment by Suburbanno** [comment]
new beta pls <3

**Comment by GLodi** [comment]
Yes! Sorry for making you wait :(. I'm almost done with the Repository activity, after that I'll publish a new release.

**Comment by Suburbanno** [comment]
:(

**Comment by GLodi** [comment]
Sorry! I've uploaded the release. The repository activity is almost working (there is still a problem when viewing repo content). I've also had to remake all the activities in the app because I decided to use a different architecture. Also all activities now support configuration change (when you rotate your device).

**Comment by Suburbanno** [comment]
themes? beta pls

**Comment by GLodi** [comment]
Hi, 
I'm applying the theme to the entire app, as soon as I'm done I'll upload a release.

**Comment by Suburbanno** [comment]
new beta release?

**Comment by GLodi** [comment]
You can find the dark theme release under the release page. The only main feature that I've added from that is the web oauth flow. After I'll have completed CommitFragment, I'll make a new release (and hopefully update it on Google Play).
